version: '3.3'

networks:
  jenkins-cluster:
    driver: overlay

services:
  jenkins:
    image: jenkins
    ports:
      - 50000:50000
      - 8080:8080
    volumes:
      - /tmp:/tmp
      - /home/ben/jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
      - /lib64/libltdl.so.7:/usr/lib/x86_64-linux-gnu/libltdl.so.7
    networks:
      - jenkins-cluster

  jenkins-agent:
    image: tview/jenkins-swarm-agent:1.0.5
    command:
      - '-master'
      - 'http://jenkins:8080'
      - '-username'
      - 'admin'
      - '-password'
      - 'admin'
    volumes:
      - /tmp:/tmp
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
      - /lib64/libltdl.so.7:/usr/lib/x86_64-linux-gnu/libltdl.so.7
    depends_on:
      - jenkins
    networks:
      - jenkins-cluster
